# Site settings
title: Bingjie Blog
SEOTitle: 冰洁的博客 | Bingjie Blog
header-img: img/home-bg.jpg
email: bingjiegao@126.com
description: "关于深度学习与量化交易、黑客与画家 | 高冰洁，Deep Learning & Quantitive Analysis，Nature Language Processing，Machine Learning | 这里是 @Diane冰洁 的个人博客，与你一起发现更大的世界。"
keyword: "冰洁, Diane冰洁, Diane, Trader, Bingjie, @bingjie, 冰洁的博客, Bingjie Blog, 博客, 个人网站, 互联网, 人工智能, 深度学习, 自然语言处理, 量化投资, 风险对冲, 一个向往远方的小白"
url: "http://mkxkx.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     446101575@qq.com
zhihu_username:     bingjie-gao
github_username:    wanwan507
#twitter_username:  huxpro
facebook_username:  Bingjie Gao

host: 0.0.0.0
port: 4000


# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

#gems
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: mkxkx.top



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，赚赚小钱，读读课本。世界那么大，我想去看看。"
sidebar-avatar: /img/avatar-bingjie.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    }
]
